"""Every figure in the repo, regenerated by one command.

Each function takes already-computed results and draws one chart. Nothing here
estimates anything: if a number appears on a figure it was produced in
:mod:`esa.study` and written to ``docs/results`` first, so the figure and the
README cannot drift apart.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.ticker import FuncFormatter, NullFormatter

from .. import config
from ..events import abnormal_return_matrix
from ..inference import SeasonStats
from ..prices import PricePanel
from . import style

WINDOW_LABELS = {0: "Day 0", 1: "Day 1", 5: "Days 1-5", 10: "Days 1-10", 20: "Days 1-20"}

#: Long daily series are drawn at this stride. Statistics are always computed
#: on the full series; only the rendered path is thinned.
DRAW_EVERY_N_SESSIONS = 5


def _source(extra: str = "") -> str:
    base = (
        "Source: SEC EDGAR 8-K item 2.02 acceptance timestamps and XBRL us-gaap EPS; "
        "prices from Yahoo Finance (split- and dividend-adjusted); factors from the "
        "Kenneth R. French Data Library. Data as of 2026-09-19."
    )
    return f"{base} {extra}".strip()


def _season_ci(
    events: pd.DataFrame, values: np.ndarray, mask: np.ndarray, *, n_boot: int, seed: int
) -> tuple[float, float, float]:
    """Mean and a season-clustered bootstrap interval for one group of events.

    Plotting a standard error computed as if the events were independent is
    the same mistake the naive t-test makes, drawn instead of written, so the
    error bars use the same cluster bootstrap the tests do.
    """
    subset = events.loc[mask].assign(_value=values[mask], category="Beat")
    stats_ = SeasonStats.build(subset, "_value")
    if stats_.n_clusters < 2:
        return float(np.nanmean(values[mask])), np.nan, np.nan
    rng = np.random.default_rng(seed)
    picks = rng.integers(0, stats_.n_clusters, size=(n_boot, stats_.n_clusters))
    beat_sum = stats_.beat_sum[picks].sum(axis=1)
    beat_n = stats_.beat_n[picks].sum(axis=1)
    draws = beat_sum / np.where(beat_n > 0, beat_n, np.nan)
    draws = draws[np.isfinite(draws)]
    point = float(np.nansum(stats_.beat_sum) / np.nansum(stats_.beat_n))
    lo, hi = np.percentile(draws, [2.5, 97.5])
    return point, float(lo), float(hi)


# ── 1. surprise against the announcement reaction ────────────────────────


def scatter_sue_vs_reaction(
    events: pd.DataFrame, path: Path, *, winsor: float = 0.01, n_bins: int = 20
) -> Path:
    """SUE against the day-0 abnormal return, at two scales.

    One panel cannot carry this. The cloud of individual events spans forty
    percentage points, and the average relationship the whole study rests on
    moves the median by about one. Drawn together on a shared axis the second
    is a flat line, which reads as "no relationship" rather than "a small one".

    So the scatter keeps its own scale on the left, and the binned conditional
    medians get theirs on the right with clustered intervals. The pair is the
    honest version: the effect is real, and it is invisible in any single
    announcement.
    """
    style.use_house_style()
    usable = events.dropna(subset=["sue", "abret_d0"]).reset_index(drop=True)
    x_all = usable["sue"].to_numpy()
    lo, hi = np.quantile(x_all, [winsor, 1 - winsor])
    keep = (x_all >= lo) & (x_all <= hi)
    usable = usable.loc[keep].reset_index(drop=True)
    x = usable["sue"].to_numpy()
    y = usable["abret_d0"].to_numpy()

    fig, (ax, ax_bin) = plt.subplots(
        1, 2, figsize=style.FIGSIZE, width_ratios=[1.55, 1.0]
    )

    ax.scatter(x, y, s=1.4, alpha=0.16, color=style.NEUTRAL, linewidths=0, rasterized=True)
    slope, intercept = np.polyfit(x, y, 1)
    grid = np.linspace(x.min(), x.max(), 160)
    ax.plot(grid, slope * grid + intercept, color=style.BEAT, linewidth=1.6)

    rng = np.random.default_rng(0)
    fits = np.empty((400, len(grid)))
    for i in range(400):
        idx = rng.integers(0, len(x), size=len(x))
        a, b = np.polyfit(x[idx], y[idx], 1)
        fits[i] = a * grid + b
    band_lo, band_hi = np.percentile(fits, [2.5, 97.5], axis=0)
    ax.fill_between(grid, band_lo, band_hi, color=style.BEAT, alpha=0.3, linewidth=0)

    corr = float(np.corrcoef(x, y)[0, 1])
    ax.axhline(0, color=style.INK, linewidth=0.8)
    ax.set_xlabel("Standardised unexpected earnings (σ)")
    ax.set_ylabel("Day-0 abnormal return (%, vs SPY)")
    ax.set_title(
        f"Every announcement    n = {len(x):,}   R² = {corr**2:.3f}",
        fontsize=style.LABEL_SIZE,
        loc="left",
        color=style.NEUTRAL,
        pad=8,
    )
    style.percent_axis(ax, decimals=0)
    style.horizontal_grid(ax)

    # Right panel: the same data, conditioned.
    edges = np.quantile(x, np.linspace(0, 1, n_bins + 1))
    which = np.clip(np.digitize(x, edges[1:-1]), 0, n_bins - 1)
    centers, medians, err_lo, err_hi = [], [], [], []
    for b in range(n_bins):
        mask = which == b
        if mask.sum() < 20:
            continue
        centers.append(float(np.median(x[mask])))
        medians.append(float(np.median(y[mask])))
        point, low, high = _season_ci(usable, y, mask, n_boot=600, seed=b)
        err_lo.append(point - low)
        err_hi.append(high - point)

    centers = np.array(centers)
    medians = np.array(medians)
    ax_bin.errorbar(
        centers,
        medians,
        yerr=[np.abs(err_lo), np.abs(err_hi)],
        fmt="o",
        markersize=4,
        color=style.MISS,
        ecolor=style.MISS,
        elinewidth=1.0,
        capsize=2.5,
        alpha=0.95,
    )
    ax_bin.plot(centers, medians, color=style.MISS, linewidth=1.3, alpha=0.6)
    ax_bin.axhline(0, color=style.INK, linewidth=0.8)
    ax_bin.set_xlabel("Standardised unexpected earnings (σ)")
    ax_bin.set_ylabel("Median day-0 abnormal return (%)")
    ax_bin.set_title(
        f"Conditional medians, {len(centers)} equal-count bins",
        fontsize=style.LABEL_SIZE,
        loc="left",
        color=style.NEUTRAL,
        pad=8,
    )
    style.percent_axis(ax_bin, decimals=1)
    style.horizontal_grid(ax_bin)
    # Share the horizontal scale so a position means the same thing in both
    # panels, even though the vertical scales deliberately differ.
    ax_bin.set_xlim(ax.get_xlim())
    ax_bin.text(
        0.97,
        0.05,
        f"median moves {medians[-1] - medians[0]:.2f} pp\nfrom the bottom bin to the top",
        transform=ax_bin.transAxes,
        ha="right",
        fontsize=style.ANNOTATION_SIZE,
        color=style.INK,
    )

    style.titles(
        fig,
        "The surprise-reaction link is clear in aggregate and invisible in any one event",
        f"{len(usable):,} S&P 500 announcements, 2012-2026, surprise winsorised at 1%/99%. "
        "Note the two vertical scales: intervals on the right are resampled by earnings season.",
    )
    style.source_note(fig, _source())
    fig.subplots_adjust(left=0.065, right=0.985, top=0.815, bottom=0.135, wspace=0.26)
    return style.save(fig, path, raster=True)


# ── 2. average return by bucket and horizon ──────────────────────────────


def bar_returns_by_bucket(
    events: pd.DataFrame, path: Path, *, windows: tuple[int, ...] = (0, 5, 20), n_boot: int = 2000
) -> Path:
    """Mean abnormal return per bucket and horizon, with clustered intervals."""
    style.use_house_style()
    fig, ax = plt.subplots(figsize=style.FIGSIZE)

    buckets = ["Miss", "In-Line", "Beat"]
    width = 0.26
    positions = np.arange(len(windows))

    for j, bucket in enumerate(buckets):
        mask = (events["category"] == bucket).to_numpy()
        means, los, his, counts = [], [], [], []
        for w in windows:
            values = events[f"abret_d{w}"].to_numpy()
            good = mask & np.isfinite(values)
            point, lo, hi = _season_ci(events, values, good, n_boot=n_boot, seed=w * 17 + j)
            means.append(point)
            los.append(point - lo)
            his.append(hi - point)
            counts.append(int(good.sum()))
        offset = (j - 1) * width
        bars = ax.bar(
            positions + offset,
            means,
            width * 0.92,
            color=style.CATEGORY_COLORS[bucket],
            label=bucket,
            zorder=3,
        )
        ax.errorbar(
            positions + offset,
            means,
            yerr=[np.abs(los), np.abs(his)],
            fmt="none",
            ecolor=style.INK,
            elinewidth=1.1,
            capsize=3,
            zorder=4,
        )
        for bar, value, count in zip(bars, means, counts):
            above = value >= 0
            ax.annotate(
                f"n={count:,}",
                (bar.get_x() + bar.get_width() / 2, 0),
                xytext=(0, -14 if above else 8),
                textcoords="offset points",
                ha="center",
                fontsize=style.ANNOTATION_SIZE - 1,
                color=style.NEUTRAL,
            )
        # Direct label, placed beyond the interval rather than on top of it.
        reach = means[-1] + (his[-1] if means[-1] >= 0 else -abs(los[-1]))
        ax.annotate(
            bucket,
            (positions[-1] + offset, reach),
            xytext=(0, 9 if means[-1] >= 0 else -17),
            textcoords="offset points",
            ha="center",
            fontsize=style.ANNOTATION_SIZE,
            fontweight="semibold",
            color=style.CATEGORY_COLORS[bucket],
        )

    ax.axhline(0, color=style.INK, linewidth=1.0)
    ax.set_xticks(positions)
    ax.set_xticklabels([WINDOW_LABELS[w] for w in windows])
    ax.set_xlabel("Horizon after the announcement (trading days)")
    ax.set_ylabel("Mean abnormal return (%, vs SPY)")
    style.percent_axis(ax)
    style.horizontal_grid(ax)
    style.titles(
        fig,
        "Most of the beat-miss gap is there on the announcement day itself",
        "Mean cumulative abnormal return from the pre-announcement close. Error bars are 95% "
        "bootstrap intervals resampled by earnings season, not by event.",
    )
    style.source_note(fig, _source())
    fig.subplots_adjust(left=0.07, right=0.975, top=0.845, bottom=0.135)
    return style.save(fig, path)


# ── 3. the drift path itself ─────────────────────────────────────────────


def cumulative_drift_paths(
    events: pd.DataFrame,
    panel: PricePanel,
    path: Path,
    *,
    max_days: int = 20,
    n_boot: int = 2000,
) -> Path:
    """Average cumulative abnormal return after the reaction close, with ribbons."""
    style.use_house_style()
    matrix = abnormal_return_matrix(events, panel, max_days=max_days, from_reaction_close=True)
    days = np.arange(max_days + 1)

    fig, ax = plt.subplots(figsize=style.FIGSIZE)
    endpoints: dict[str, float] = {}
    for bucket in ("Beat", "Miss"):
        mask = (events["category"] == bucket).to_numpy()
        means, los, his = [], [], []
        for w in days:
            values = matrix[:, w]
            good = mask & np.isfinite(values)
            point, lo, hi = _season_ci(events, values, good, n_boot=n_boot, seed=int(w))
            means.append(point)
            los.append(lo)
            his.append(hi)
        color = style.CATEGORY_COLORS[bucket]
        ax.plot(days, means, color=color, marker=style.CATEGORY_MARKERS[bucket], markersize=3.5)
        ax.fill_between(days, los, his, color=color, alpha=0.18, linewidth=0)
        endpoints[bucket] = means[-1]
        ax.annotate(
            bucket,
            (days[-1], means[-1]),
            xytext=(8, 0),
            textcoords="offset points",
            va="center",
            fontsize=style.ANNOTATION_SIZE,
            fontweight="semibold",
            color=color,
        )

    ax.axhline(0, color=style.INK, linewidth=1.0)
    ax.set_xlim(-0.5, max_days + 1.8)
    ax.set_xticks(np.arange(0, max_days + 1, 2))
    ax.set_xlabel("Trading days after the first tradeable close")
    ax.set_ylabel("Mean cumulative abnormal return (%, vs SPY)")
    style.percent_axis(ax)
    style.horizontal_grid(ax)
    spread = endpoints.get("Beat", float("nan")) - endpoints.get("Miss", float("nan"))
    style.titles(
        fig,
        "After the announcement day the two groups separate by well under a percent",
        "Cumulative abnormal return measured from the close of the first session the market could "
        "react in, so the announcement jump is excluded. Ribbons are 95% season-clustered bootstrap "
        f"intervals. The gap reaches {spread:+.2f} pp after 20 sessions.",
    )
    style.source_note(fig, _source())
    fig.subplots_adjust(left=0.07, right=0.955, top=0.845, bottom=0.135)
    return style.save(fig, path)


# ── 4. distributions ─────────────────────────────────────────────────────


def return_distributions(events: pd.DataFrame, path: Path, *, metric: str = "abdrift_d20") -> Path:
    """Two kernel densities and a rug, on one panel, with the mean gap annotated."""
    style.use_house_style()
    fig, ax = plt.subplots(figsize=style.FIGSIZE)

    from scipy.stats import gaussian_kde

    usable = events.dropna(subset=[metric])
    lo, hi = np.quantile(usable[metric], [0.005, 0.995])
    grid = np.linspace(lo, hi, 256)
    rng = np.random.default_rng(7)

    means = {}
    for bucket in ("Beat", "Miss"):
        full = usable.loc[usable["category"] == bucket, metric].to_numpy()
        values = full[(full >= lo) & (full <= hi)]
        if len(values) < 10:
            continue
        density = gaussian_kde(values)(grid)
        color = style.CATEGORY_COLORS[bucket]
        ax.plot(grid, density, color=color)
        ax.fill_between(grid, density, color=color, alpha=0.14, linewidth=0)
        # The mean is taken on the untrimmed group, so the gap quoted here is
        # the same number the results table reports. Only the density is
        # trimmed, and only so the tails do not flatten the picture.
        means[bucket] = float(full.mean())
        ax.axvline(means[bucket], color=color, linestyle="--", linewidth=1.2)
        # One line collection rather than several hundred separate marker
        # paths: same picture, a fraction of the file.
        rug = values[rng.integers(0, len(values), size=min(300, len(values)))]
        base = -0.0016 if bucket == "Beat" else -0.0032
        ax.vlines(rug, base - 0.0006, base + 0.0006, color=color, alpha=0.35, linewidth=0.6)
        ax.annotate(
            bucket,
            (grid[np.argmax(density)], density.max()),
            xytext=(0, 6),
            textcoords="offset points",
            ha="center",
            fontsize=style.ANNOTATION_SIZE,
            fontweight="semibold",
            color=color,
        )

    if len(means) == 2:
        gap = means["Beat"] - means["Miss"]
        ax.text(
            0.985,
            0.93,
            f"mean gap = {gap:+.2f} pp\nagainst a spread of ±{np.std(usable[metric]):.0f} pp per event\n"
            "(means on untrimmed groups)",
            transform=ax.transAxes,
            ha="right",
            fontsize=style.ANNOTATION_SIZE,
            color=style.INK,
        )

    ax.set_ylim(bottom=-0.005)
    ax.set_xlabel("20-day abnormal return after the first tradeable close (%, vs SPY)")
    ax.set_ylabel("Density")
    style.percent_axis(ax, axis="x", decimals=0)
    style.horizontal_grid(ax)
    style.titles(
        fig,
        "The two outcome distributions overlap almost completely",
        "Kernel densities of post-announcement drift, trimmed at the 0.5th and 99.5th percentiles. "
        "Dashed lines are group means; rug marks are a random sample of individual events.",
    )
    style.source_note(fig, _source())
    fig.subplots_adjust(left=0.07, right=0.975, top=0.845, bottom=0.135)
    return style.save(fig, path)


# ── 5. quintile heatmap ──────────────────────────────────────────────────


def sue_quintile_heatmap(
    events: pd.DataFrame, path: Path, *, windows: tuple[int, ...] = (0, 1, 5, 10, 20), min_n: int = 100
) -> Path:
    """Mean abnormal return by SUE quintile and horizon."""
    style.use_house_style()
    usable = events.dropna(subset=["sue"]).copy()
    usable["quintile"] = pd.qcut(usable["sue"], 5, labels=["Q1", "Q2", "Q3", "Q4", "Q5"])

    rows = ["Q5", "Q4", "Q3", "Q2", "Q1"]
    values = np.full((len(rows), len(windows)), np.nan)
    counts = np.zeros_like(values, dtype=int)
    for i, quintile in enumerate(rows):
        subset = usable[usable["quintile"] == quintile]
        for j, w in enumerate(windows):
            column = subset[f"abret_d{w}"].dropna()
            counts[i, j] = len(column)
            values[i, j] = column.mean() if len(column) else np.nan

    display = np.where(counts >= min_n, values, np.nan)
    fig, ax = plt.subplots(figsize=style.FIGSIZE)
    mesh = ax.imshow(
        display, cmap=style.DIVERGING, norm=style.diverging_norm(display), aspect="auto"
    )
    ax.set_xticks(range(len(windows)), [WINDOW_LABELS[w] for w in windows])
    ax.set_yticks(range(len(rows)), [f"{q} ({'most negative' if q == 'Q1' else 'most positive' if q == 'Q5' else 'middle'})" if q in ("Q1", "Q5") else q for q in rows])
    ax.grid(False)

    for i in range(len(rows)):
        for j in range(len(windows)):
            if counts[i, j] < min_n:
                ax.add_patch(plt.Rectangle((j - 0.5, i - 0.5), 1, 1, color="#EDEDED", zorder=2))
                ax.text(j, i, f"n={counts[i, j]}\ntoo few", ha="center", va="center", fontsize=style.ANNOTATION_SIZE - 1, color=style.NEUTRAL, zorder=3)
                continue
            shade = abs(values[i, j]) / max(np.nanmax(np.abs(display)), 1e-9)
            ax.text(
                j,
                i,
                f"{values[i, j]:+.2f}%\nn={counts[i, j]:,}",
                ha="center",
                va="center",
                fontsize=style.ANNOTATION_SIZE,
                color="white" if shade > 0.55 else style.INK,
                zorder=3,
            )

    bar = fig.colorbar(mesh, ax=ax, pad=0.015, fraction=0.03)
    bar.set_label("Mean abnormal return (%)", size=style.LABEL_SIZE)
    bar.outline.set_visible(False)
    ax.set_xlabel("Horizon after the announcement (trading days)")
    ax.set_ylabel("Surprise quintile")
    style.titles(
        fig,
        "The gradient across surprise quintiles is monotonic at every horizon, and widens",
        f"Mean cumulative abnormal return from the pre-announcement close, by SUE quintile. Cells "
        f"with fewer than {min_n} events are greyed out. Colour is pinned at zero.",
    )
    style.source_note(fig, _source())
    fig.subplots_adjust(left=0.155, right=0.935, top=0.845, bottom=0.135)
    return style.save(fig, path)


# ── 6. the book ──────────────────────────────────────────────────────────


def backtest_equity(
    daily: pd.DataFrame, panel: PricePanel, metrics: dict[str, float], path: Path
) -> Path:
    """Gross and net equity against SPY, with a drawdown panel beneath."""
    style.use_house_style()
    traded = daily[daily["net_ret"].notna()]
    fig, (ax, ax_dd) = plt.subplots(
        2, 1, figsize=style.FIGSIZE, sharex=True, height_ratios=[2.6, 1.0]
    )

    gross = (1.0 + traded["gross_ret"].fillna(0.0)).cumprod()
    net = (1.0 + traded["net_ret"].fillna(0.0)).cumprod()

    # Every statistic on this chart is computed on the daily series above.
    # The curves are *drawn* every fifth session, because at the width GitHub
    # renders this the two are the same picture and the daily version costs
    # several hundred kilobytes of path data.
    def thin(series: pd.Series) -> pd.Series:
        return series.iloc[::DRAW_EVERY_N_SESSIONS]

    # Growth of a dollar on a log scale. On a linear cumulative-return axis a
    # benchmark that compounds to 7.6x flattens a strategy that compounds to
    # 1.3x into the floor, and the strategy's own drawdowns become unreadable.
    # The log axis keeps the 6x gap obvious while leaving both shapes legible.
    ax.plot(thin(net).index, thin(net), color=style.BEAT)
    ax.plot(thin(gross).index, thin(gross), color=style.NEUTRAL, linewidth=1.2, linestyle=(0, (4, 2)))

    bench = panel.close.get("SPY")
    if bench is not None:
        window = bench.loc[traded.index[0] : traded.index[-1]].dropna()
        bench_curve = (window / window.iloc[0]).iloc[::DRAW_EVERY_N_SESSIONS]
        ax.plot(bench_curve.index, bench_curve, color=style.INLINE, linewidth=1.4)
        ax.annotate(
            f"SPY buy and hold, {bench_curve.iloc[-1]:.1f}x",
            (bench_curve.index[-1], bench_curve.iloc[-1]),
            xytext=(-6, 6),
            textcoords="offset points",
            ha="right",
            fontsize=style.ANNOTATION_SIZE,
            fontweight="semibold",
            color=style.INLINE,
        )

    for series, label, color, dy in (
        (gross, "strategy, gross", style.NEUTRAL, 9),
        (net, "strategy, net of costs", style.BEAT, -14),
    ):
        ax.annotate(
            f"{label}, {series.iloc[-1]:.2f}x",
            (series.index[-1], series.iloc[-1]),
            xytext=(-6, dy),
            textcoords="offset points",
            ha="right",
            fontsize=style.ANNOTATION_SIZE,
            fontweight="semibold",
            color=color,
        )

    ax.set_yscale("log")
    ax.axhline(1.0, color=style.INK, linewidth=0.9)
    ax.set_ylabel("Growth of $1 (log scale)")
    ax.set_yticks([0.8, 1, 1.5, 2, 3, 5, 8])
    ax.yaxis.set_major_formatter(FuncFormatter(lambda v, _: f"{v:g}x"))
    ax.yaxis.set_minor_formatter(NullFormatter())
    ax.set_ylim(0.75, 11)
    style.horizontal_grid(ax)

    peak = net.cummax()
    drawdown = (net / peak - 1.0) * 100
    drawn = drawdown.iloc[::DRAW_EVERY_N_SESSIONS]
    ax_dd.fill_between(drawn.index, drawn, 0, color=style.MISS, alpha=0.35, linewidth=0)
    ax_dd.plot(drawn.index, drawn, color=style.MISS, linewidth=1.0)
    trough = drawdown.idxmin()
    peak_date = net.loc[:trough].idxmax()
    ax_dd.axvspan(peak_date, trough, color=style.MISS, alpha=0.12, linewidth=0)
    ax_dd.annotate(
        f"deepest drawdown {drawdown.min():.1f}%, {peak_date:%b %Y} to {trough:%b %Y}",
        (trough, drawdown.min()),
        xytext=(14, 10),
        textcoords="offset points",
        ha="left",
        va="bottom",
        fontsize=style.ANNOTATION_SIZE,
        fontweight="semibold",
        color=style.MISS,
    )
    ax_dd.set_ylabel("Drawdown (%)")
    ax_dd.set_xlabel("")
    style.percent_axis(ax_dd, decimals=0)
    style.horizontal_grid(ax_dd)

    sharpe = metrics.get("sharpe", float("nan"))
    total = metrics.get("total_return_pct", float("nan"))
    bench_total = metrics.get("benchmark_total_return_pct", float("nan"))
    style.titles(
        fig,
        "A measurable effect that does not survive contact with a book",
        f"Long beats, short misses, {int(metrics.get('n_trades', 0)):,} positions held 20 sessions, "
        f"equal-weighted across whatever is live and marked daily. Net {total:+.1f}% against SPY "
        f"{bench_total:+.1f}% over the same span, at a Sharpe of {sharpe:.2f} on daily excess returns.",
    )
    style.source_note(
        fig,
        _source(
            f"Round-trip cost {metrics.get('round_trip_cost_bps', 0):.0f} bp. Series computed daily, "
            f"drawn every {DRAW_EVERY_N_SESSIONS}th session."
        ),
    )
    fig.subplots_adjust(left=0.085, right=0.975, top=0.845, bottom=0.105, hspace=0.12)
    return style.save(fig, path)


# ── 7. decay ─────────────────────────────────────────────────────────────


def decay_curve(curve: pd.DataFrame, trend: dict[str, float], path: Path) -> Path:
    """Rolling three-year beat-minus-miss drift, with a bootstrap band."""
    style.use_house_style()
    fig, ax = plt.subplots(figsize=style.FIGSIZE)
    dates = pd.to_datetime(curve["end_date"])

    ax.fill_between(dates, curve["ci_low"], curve["ci_high"], color=style.BEAT, alpha=0.2, linewidth=0)
    ax.plot(dates, curve["spread"], color=style.BEAT)
    ax.axhline(0, color=style.INK, linewidth=1.0)

    ax.annotate(
        "rolling 3-year\nbeat − miss drift",
        (dates.iloc[-1], curve["spread"].iloc[-1]),
        xytext=(-10, -26),
        textcoords="offset points",
        ha="right",
        fontsize=style.ANNOTATION_SIZE,
        fontweight="semibold",
        color=style.BEAT,
    )
    peak_idx = int(curve["spread"].idxmax())
    style.callout(
        ax,
        f"peak {curve['spread'].max():+.2f} pp\n({curve['season'].iloc[peak_idx]})",
        xy=(dates.iloc[peak_idx], curve["spread"].max()),
        xytext=(dates.iloc[max(peak_idx - 14, 0)], curve["ci_high"].max() * 0.92),
    )

    ax.set_xlabel("End of the three-year window")
    ax.set_ylabel("Beat − Miss 20-day drift (percentage points)")
    style.percent_axis(ax, decimals=1)
    style.horizontal_grid(ax)
    slope = trend.get("slope_pp_per_decade", float("nan"))
    style.titles(
        fig,
        "Drift strengthened into the early 2020s and has since faded back",
        f"Beat-minus-Miss cumulative abnormal return over the 20 sessions after the first tradeable "
        f"close, on a rolling three-year window stepped one earnings season at a time. Band is a 90% "
        f"season-clustered bootstrap interval. Linear trend {slope:+.2f} pp per decade.",
    )
    style.source_note(
        fig,
        _source("Windows overlap by eleven of twelve seasons, so neighbouring points are not independent."),
    )
    fig.subplots_adjust(left=0.075, right=0.975, top=0.835, bottom=0.135)
    return style.save(fig, path)


# ── 8. where the move happens ────────────────────────────────────────────


def gap_versus_drift(decomposition: pd.DataFrame, path: Path) -> Path:
    """Split the beat-miss spread into gap, first session, and subsequent drift."""
    style.use_house_style()
    fig, ax = plt.subplots(figsize=style.FIGSIZE)

    spread = decomposition[decomposition["category"] == "Beat - Miss"]
    if spread.empty:
        raise ValueError("decomposition is missing the Beat - Miss row")
    row = spread.iloc[0]
    drift_col = next(c for c in decomposition.columns if c.startswith("drift_d"))

    parts = [
        ("Overnight gap\n(not fillable)", float(row["gap_pct"]), style.NEUTRAL),
        ("First session,\nopen to close", float(row["open_to_close_pct"]), style.INLINE),
        ("Drift over the\nnext 20 sessions", float(row[drift_col]), style.BEAT),
    ]
    order = sorted(parts, key=lambda p: -abs(p[1]))
    labels = [p[0] for p in order]
    values = [p[1] for p in order]
    colors = [p[2] for p in order]

    bars = ax.barh(range(len(values)), values, color=colors, height=0.55, zorder=3)
    for i, (bar, value) in enumerate(zip(bars, values)):
        ax.annotate(
            f"{value:+.2f} pp",
            (value, i),
            xytext=(6 if value >= 0 else -6, 0),
            textcoords="offset points",
            va="center",
            ha="left" if value >= 0 else "right",
            fontsize=style.ANNOTATION_SIZE,
            fontweight="semibold",
            color=style.INK,
        )
    gap_row = next(i for i, label in enumerate(labels) if "not fillable" in label)
    # The text sits in the white space below the bar, so it is drawn in ink
    # and the leader runs up into the bar rather than the other way round.
    style.callout(
        ax,
        "already in the opening print: no strategy\nreacting to the release can capture it",
        xy=(values[gap_row] * 0.62, gap_row + 0.28),
        xytext=(values[gap_row] * 0.04, gap_row + 0.62),
        color=style.INK,
    )
    ax.set_yticks(range(len(labels)), labels)
    ax.invert_yaxis()
    ax.axvline(0, color=style.INK, linewidth=1.0)
    ax.grid(True, axis="x", color=style.GRID, linewidth=0.8)
    ax.grid(False, axis="y")
    ax.set_xlabel("Beat − Miss spread (percentage points, vs SPY)")
    total = sum(values)
    tradeable = sum(v for label, v, _ in order if "not fillable" not in label)
    share = tradeable / total * 100 if total else float("nan")
    style.titles(
        fig,
        "About half the beat-miss spread is gone before anyone can trade it",
        f"Total spread {total:+.2f} pp, of which {tradeable:+.2f} pp ({share:.0f}%) is reachable at "
        f"the earliest fillable price. n = {int(row['n']):,} beat and miss announcements.",
    )
    style.source_note(fig, _source())
    fig.subplots_adjust(left=0.185, right=0.955, top=0.845, bottom=0.135)
    return style.save(fig, path)


# ── 9. break-even cost ───────────────────────────────────────────────────


def breakeven_cost(curve: pd.DataFrame, breakeven: dict[str, float], path: Path) -> Path:
    """Net total return as a function of round-trip cost, with break-even marked.

    The interesting region is the first few tens of basis points. Past that
    both curves are pinned near total loss and the only thing extra width buys
    is empty grid, so the axis stops where the answer stops changing.
    """
    style.use_house_style()
    fig, ax = plt.subplots(figsize=style.FIGSIZE)

    series = [
        ("next_open", "net_total_return_pct_next_open", style.OKABE_ITO["green"], "Enter at the next open"),
        ("next_close", "net_total_return_pct_next_close", style.BEAT, "Enter at the next close"),
    ]
    x_max = 60.0
    drawn = curve[curve["round_trip_bps"] <= x_max]

    for key, column, color, label in series:
        if column not in curve.columns:
            continue
        ax.plot(drawn["round_trip_bps"], drawn[column], color=color, marker="o", markersize=4)
        # Labelled at the left end, where the two curves are furthest apart.
        ax.annotate(
            label,
            (drawn["round_trip_bps"].iloc[0], drawn[column].iloc[0]),
            xytext=(22, 3),
            textcoords="offset points",
            ha="left",
            va="bottom",
            fontsize=style.ANNOTATION_SIZE,
            fontweight="semibold",
            color=color,
        )
        point = breakeven.get(key, float("nan"))
        if np.isfinite(point) and point > 0:
            ax.plot([point], [0.0], marker="D", markersize=6, color=color, zorder=5)
            ax.vlines(point, 0, drawn[column].iloc[0] * 0.42, color=color, linestyle=":", linewidth=1.1)
            ax.annotate(
                f"break-even\n{point:.0f} bp",
                (point, drawn[column].iloc[0] * 0.42),
                xytext=(0, 6),
                textcoords="offset points",
                ha="center",
                fontsize=style.ANNOTATION_SIZE,
                color=color,
            )

    assumed = 5.0
    ax.axvline(assumed, color=style.INK, linewidth=1.0, alpha=0.45)
    ax.annotate(
        f"this study assumes {assumed:.0f} bp",
        (assumed, ax.get_ylim()[0]),
        xytext=(6, 14),
        textcoords="offset points",
        ha="left",
        fontsize=style.ANNOTATION_SIZE,
        color=style.INK,
    )

    ax.axhline(0, color=style.INK, linewidth=1.0)
    ax.set_xlim(-1.5, x_max)
    ax.set_xlabel("Assumed round-trip cost (basis points of notional)")
    ax.set_ylabel("Net total return over the sample (%)")
    style.percent_axis(ax, decimals=0)
    style.horizontal_grid(ax)
    style.titles(
        fig,
        "The edge clears a realistic cost assumption, and not by much",
        "Total net return of the long-beat/short-miss book against an assumed round-trip cost, with "
        "everything else held fixed. Borrow on the short leg is charged separately and is not part "
        f"of the horizontal axis. Curves are truncated at {x_max:.0f} bp, beyond which both are near "
        "total loss.",
    )
    style.source_note(
        fig,
        _source("A 1-3 bp quoted spread in S&P 500 names implies roughly 4-8 bp round trip including commission and impact."),
    )
    fig.subplots_adjust(left=0.085, right=0.975, top=0.815, bottom=0.135)
    return style.save(fig, path)


# ── driver ───────────────────────────────────────────────────────────────


def build_all(results: object, panel: PricePanel, out_dir: Path | None = None) -> list[Path]:
    """Regenerate every figure from a :class:`~esa.study.StudyResults`."""
    out_dir = out_dir or config.FIGURES_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    r = results  # narrow alias; typed loosely to avoid a circular import

    written = [
        scatter_sue_vs_reaction(r.events, out_dir / "01_surprise_vs_reaction.png"),  # type: ignore[attr-defined]
        bar_returns_by_bucket(r.events, out_dir / "02_returns_by_bucket.svg"),  # type: ignore[attr-defined]
        cumulative_drift_paths(r.events, panel, out_dir / "03_drift_paths.svg"),  # type: ignore[attr-defined]
        return_distributions(r.events, out_dir / "04_return_distributions.svg"),  # type: ignore[attr-defined]
        sue_quintile_heatmap(r.events, out_dir / "05_quintile_heatmap.svg"),  # type: ignore[attr-defined]
        backtest_equity(
            r.backtests["next_close"].daily,  # type: ignore[attr-defined]
            panel,
            r.backtests["next_close"].metrics,  # type: ignore[attr-defined]
            out_dir / "06_backtest_equity.svg",
        ),
        decay_curve(r.decay_curve, r.decay_trend, out_dir / "07_decay.svg"),  # type: ignore[attr-defined]
        gap_versus_drift(r.decomposition, out_dir / "08_gap_vs_drift.svg"),  # type: ignore[attr-defined]
        breakeven_cost(r.cost_curve, r.breakeven_bps, out_dir / "09_breakeven_cost.svg"),  # type: ignore[attr-defined]
    ]
    for figure in written:
        config.write_provenance(
            figure,
            command="python main.py figures",
            data_source="docs/results/*.csv and output/event_panel.parquet",
            as_of="2026-09-19",
        )
    return written
